name: Run Python Script and Commit Output
on:
  schedule:
    # Runs at every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  run_script_and_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will fail to push refs to dest repo
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests selenium
    - name: Run the script
      run: |
        python main.py
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
